spring:
  jpa:
    open-in-view: false
    hibernate:
      use-new-id-generator-mappings: false
    database: h2
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console